### ISSUE TITLE
Compatibility patch breaks other tracking tools

### ISSUE THREAD

**Issue by ShereKahn** [stevschmid/track-o-bot#100]
Hello Steve, I was trying to use both HSTracker and track-o-bot as I find both valuable. 

track-o-bot uses the logs produced by FilePrinting, whereas the other tool is using the ConsolePrinting.

The problem I am seeing is that track-o-bot disables Console printing at startup, in Hearthstone.cpp lines 132 and subsequent: 

```
 QRegExp regexEnabledConsolePrinting( "ConsolePrinting\\s*=\\s*true",
      Qt::CaseInsensitive );
  QRegExp regexDisabledFilePrinting( "FilePrinting\\s*=\\s*false",
      Qt::CaseInsensitive );
  if( contents.contains( regexEnabledConsolePrinting ) ||
      contents.contains( regexDisabledFilePrinting ) )
  {
    contents.replace( regexEnabledConsolePrinting, "FilePrinting=true" );   // <<=== here
    contents.replace( regexDisabledFilePrinting, "FilePrinting=true" );
```

This results in a log.config two  with "FilePrinting=true" lines whenever ConsolePrinting is enabled and as a consequence disables ConsolePrinting. 

I believe that removing the marked line here above will avoid disabling console printing  when it is enabled. 

I am not sure if this is really what is intended (why would we want to disable consoleprinting if it is enabled?) but I would appreciate if this could be fixed in future releases. 

Thanks 
Alain

**Comment by stevschmid** [comment]
Every tool should move to file printing because console printing leads to stutter and lag (even when it's not noticeable for some people, it definitely impacts the performance).

**Comment by ShereKahn** [comment]
Ok I understand that. 

However it seems to be a bad practise to change things based on what your view is is best.

It seems to me that one tool should not impose on what other tools are doing. 

Thanks
Alain

**Comment by stevschmid** [comment]
The code above is the upgrade path for log.config. It assumes Track-o-Bot wrote the config (albeit it is somewhat flexible in case an old tool wrote i). I don't have the resources to support multiple tools (and I'm personally not a fan of deck tracking / hud overlays). I try to avoid breaking things, but this change is for the best in the interest for the user (namely, no lag/stutter/performance decrease). I suggest you deinstall Track-o-Bot until all your other tools are updated in this regard.
