### ISSUE TITLE
[Question] which information is captured using screencapture?

### ISSUE THREAD

**Issue by joecabezas** [stevschmid/track-o-bot#102]
Hello, after reading this:

https://www.reddit.com/r/hearthstone/comments/26ptaa/introducing_trackobot_a_simple_opensource_app/

"The ingame logs are parsed for a history of the played cards, whereas other informations are gathered by screen capture."

I want to know which information specifically is being gathered by screen capture, thanks!

**Comment by stevschmid** [comment]
The only thing which is done via screen capture is rank detection. Everything else is done via log. Does that answer your question?

**Comment by joecabezas** [comment]
yes thanks, I am just learning how to scrap information from games using screenshot, and I wanted to understand more your code, how do you read numbers?, specifically in which part (of the game) do you read the rank?

**Comment by stevschmid** [comment]
The [RankClassifer](https://github.com/stevschmid/track-o-bot/blob/master/src/RankClassifier.h) uses a [Multilayer perceptron](https://github.com/stevschmid/track-o-bot/blob/master/src/MLP.h) to obtain the rank of the player (the ranks look [this](http://hydra-media.cursecdn.com/hearthstone.gamepedia.com/thumb/b/b3/Ranks.jpg/325px-Ranks.jpg?version=1edf78c4b6a8eabab73be262630696c2)). The weights for the MLP were pretrained with a python script using [sknn.mlp](http://scikit-neuralnetwork.readthedocs.org/en/latest/module_mlp.html). Hope that helps.
