### ISSUE TITLE
Track-o-Bot 0.6.2 corrupts log.config

### ISSUE THREAD

**Issue by ovidiusoft** [stevschmid/track-o-bot#103]
When started, Tack-o-Bot corrupts the following `log.config`

<pre>
[Zone]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false
[Bob]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false
[Power]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false
[Asset]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false
[Rachelle]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false
[Arena]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false
</pre>

It will replace all occurences of `ConsolePrinting=true` with `FilePrinting=true`, duplicating the `FilePrinting` lines:

<pre>
[Zone]
LogLevel=1
FilePrinting=true
FilePrinting=true
ScreenPrinting=false
[Bob]
LogLevel=1
FilePrinting=true
FilePrinting=true
ScreenPrinting=false
[Power]
LogLevel=1
FilePrinting=true
FilePrinting=true
ScreenPrinting=false
[Asset]
LogLevel=1
FilePrinting=true
FilePrinting=true
ScreenPrinting=false
[Rachelle]
LogLevel=1
FilePrinting=true
FilePrinting=true
ScreenPrinting=false
[Arena]
LogLevel=1
FilePrinting=true
FilePrinting=true
ScreenPrinting=false
</pre>

**Comment by stevschmid** [comment]
This is intended (it looks ugly but does not affect the functionality). The reason is simple: I don't know which app created the log.config. I can only assume Track-o-Bot. And to make sure people do not experience the lag issue anymore I need to disable `ConsolePrinting`.

**Comment by ovidiusoft** [comment]
Would it be possible to have a setting that disables altering the log file? Something like "Don't change log.config, I KNOW WHAT I'M DOING" :) It would be useful for us users who don't experience any lag and do need the file to contain `ConsolePrinting=true`. Thank you!
