### ISSUE TITLE
Re-index results from the desks list

### ISSUE THREAD

**Issue by ovidiusoft** [stevschmid/track-o-bot#104]
As a user,
I would like to force the app to re-index the decks from my matches history after I edit the decks list.

(A "Reindex" button would be enough, it doesn't have to be instant).

**Comment by oker1** [comment]
:+1: , it was nice when it was matched on the fly, seems like a while ago the decks became permanent.

**Comment by stevschmid** [comment]
I'm considering this for the next update!

**Comment by stevschmid** [comment]
I'm planning on revamping the whole deck system on the website.
