### ISSUE TITLE
Suggestion: "Add as Deck"

### ISSUE THREAD

**Issue by Frozen-byte** [stevschmid/track-o-bot#105]
I would like to see a "Add this Cards as a new Deck" button when I open the "Card history" Panel.
This is the most easy way to fill your Decklist easily.

I attached an example of the Link-placement:
![kvvcoz](https://cloud.githubusercontent.com/assets/3965439/10373303/e883190c-6dec-11e5-9813-7d77e2bec257.png)

**Comment by stevschmid** [comment]
Thanks for your suggestion. The problem I see with it that a deck in Track-o-Bot is recognized via several key cards which make up for the deck archetype. Defining complete (or close to complete) decks in Track-o-Bot makes the recognition inaccurate.

**Comment by Frozen-byte** [comment]
You are right, there is no sense to add similar deck's - track-o-bot can't differ them.
I'm not aware how "smart" recognition is, in my imagination the played cards are compared to the decklists and that deck with he highest intersection "wins".

So it is necessary to edit the deck after adding. Maybe the link just refers you to a pre-filled form in the deck creator?

**Comment by stevschmid** [comment]
I'm planning on revamping the whole deck system on the website.
