### ISSUE TITLE
How to enter results manual?

### ISSUE THREAD

**Issue by bl4ck0r** [stevschmid/track-o-bot#108]
Hi All! I love the app but cause of playing much on my phone i want to add game results manual. How can i do this? A small button or menu on the profile page would be nice to add a game!

thanks

**Comment by stevschmid** [comment]
There is currently no way to enter results manually. The API supports adding results though, so I hope somebody out there will release a cool iOS/Android app someday.

**Comment by serkrapiv** [comment]
@stevschmid where can I read about API possibilities? Would be super cool. So far the only thing I've seen is this: https://trackobot.com/profile/settings/api. But there isn't much info.

**Comment by stevschmid** [comment]
@serkrapiv https://gist.github.com/stevschmid/120adcbc5f1f7cb31bc5
