### ISSUE TITLE
causes battery drain during sleep on mac laptop

### ISSUE THREAD

**Issue by mscholtz** [stevschmid/track-o-bot#109]
I've noticed that if I leave T-o-B running when I close the lid of my laptop, the battery always drains significantly while it's asleep.  If i quit ToB first, the drain does not happen.  I've verified this several times, and ToB definitely seems to be the culprit.

I'm on a Macbook Air (circa 2013), running Yosemite

Would love if you could fix this, if possible.  ToB is great, but this has resulted in a dead battery several times.

**Comment by stevschmid** [comment]
Thanks for the report. I will try to improve the performance in the upcoming version (especially on OS X).

**Comment by stevschmid** [comment]
The idle wake ups were heavily reduced with 0.7.x. The newest version (0.7.1) will soon be added to the auto-update queue.
