### ISSUE TITLE
Track-o-bot / HSTracker

### ISSUE THREAD

**Issue by bmichotte** [stevschmid/track-o-bot#110]
Hi @stevschmid,

I have a lot of issue with [HSTracker](https://github.com/bmichotte/HSTracker) due to Track-o-bot rewriting `log.config`.

Latest HSTracker release also use `FilePrinting=true` but I need more modules than you, so could you please considerate adding `Rachelle` and `Arena` in your config ?

Thanks !

**Comment by stevschmid** [comment]
Hi Ben

Track-o-Bot is very flexible regarding the log.config, i.e. it extends the list of modules which are needed, but does not remove the other (excessive) ones. What that means is that it does not remove any modules required by any other tool. So you should be fine if you extend the log.config yourself.
