### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by dogancan** [stevschmid/track-o-bot#111]
Track-o-bot has relatively high CPU usage on my rMBP. I first noticed this after upgrading to El Capitan but I don't know if that is relevant. It seems track-o-bot's CPU usage spikes every few seconds. Activity monitor's energy tab is reporting that track-o-bot uses more energy than Safari (my main browser) on average.

**Comment by stevschmid** [comment]
Thanks for the report. Will check it out and address it for the next update.

**Comment by stevschmid** [comment]
The idle wake ups were heavily reduced. The newest version (0.7.1) featuring this will soon be added to the auto-update queue.

**Comment by dogancan** [comment]
Thanks for looking into this. I just updated to version 0.7.1 but I am still seeing the same CPU usage spikes every few seconds even when the game is not running.

**Comment by schubter** [comment]
![bildschirmfoto 2016-02-19 um 09 24 05](https://cloud.githubusercontent.com/assets/612475/13170183/8ec4d560-d6ea-11e5-9821-19aa4a479efb.png)

this is what i see (`sudo opensnoop -n Track-o-Bot`) prior seeing the cpu spike in activity monitor, perhaps its not the log file check thats causing the spikes but rather a network request

**Comment by valyard** [comment]
Yeah, the app stays at 60-80% CPU no matter what. Even more than Hearthstone itself.

**Comment by PerilousApricot** [comment]
I see this as well under 0.7.1. Watching under dtruss, it appears it sleeps for a while with no usage, then a thread wakes up and does what appears to be a query for all of the network interfaces.

**Comment by stevschmid** [comment]
Thanks for all the infos guys! I was finally able to track down this issue on my MacBook (it only affects MacBooks). It's a reported [Qt issue](https://bugreports.qt.io/browse/QTBUG-50181?focusedCommentId=312448&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-312448) and will hopefully get fixed shortly. In the meantime I will bundle new Track-o-Bot versions with Qt5 libs which have bearer management disabled (and thus do not poll the network interfaces all the time). Stay tuned for the new version which will get released soon!
