### ISSUE TITLE
Bad rank icon on website (6)

### ISSUE THREAD

**Issue by Pwter** [stevschmid/track-o-bot#112]
It has a 9 rank icon instead of 6, on the website.

**Comment by oker1** [comment]
I can confirm:
![](http://puu.sh/lsNwE/6a56a231da.png)

**Comment by stevschmid** [comment]
Thanks for reporting this issue. Will adress it in a upcoming update.

**Comment by RobErskine** [comment]
No rush, but I can also confirm. Running 0.6.2 on Max OS 10.10.3 if that helps at all.

**Comment by asiertejada** [comment]
+1 here

**Comment by stevschmid** [comment]
The new version 0.7.1 features a much more robust rank detection system. It will soon be added to the auto-update queue.
