### ISSUE TITLE
Adding additional games (played outside PC/Mac)

### ISSUE THREAD

**Issue by spam8117** [stevschmid/track-o-bot#114]
I don't know if this is already in the works (or even already possible) but is there a possibility to add custom games (played on iPad etc.)? Just Deck A vs. Deck B and Ranked/Casual...Win/Loss

Thanks :)

**Comment by stevschmid** [comment]
Unfortunately no. Trackobot.com offers a fully fledged API (which includes the ability to create new games) and my hope is still that someone makes a cool android/iOS app.
