### ISSUE TITLE
Doesn't recognize time zone

### ISSUE THREAD

**Issue by mscholtz** [stevschmid/track-o-bot#116]
It's still november in my time zone (pacific) but it's after midnight on Dec 1 in eastern time zone.  When I go to stats and request Current Month, it only shows me games from the last hour or so.  Clearly it thinks Current Month = December.  Would be better if it would either respect my machine's TZ or let me set it in my account settings.

**Comment by mscholtz** [comment]
Now I'm thinking I misdiagnosed this, unless you're using a European time zone or something.  I just tried doing the custom date range extending into today, and it's not including games from late afternoon today.  So maybe the custom date range feature is just buggy?

**Comment by stevschmid** [comment]
The server time is CET. I don't have the resources to address this issue at the moment, but I will keep it in mind for the future.
