### ISSUE TITLE
Ranks are no longer showing (also lost old tracked ranks)

### ISSUE THREAD

**Issue by spam8117** [stevschmid/track-o-bot#117]
Since today (didn't play much) there are no ranks recorded for ranked play anymore.
Also, already tracked ranks (see screenshot, November 26th etc.) are now missing as well.
![capture](https://cloud.githubusercontent.com/assets/10722935/11556824/88f29cae-99a9-11e5-8918-2b304d39ed5f.PNG)

**Comment by stevschmid** [comment]
Rank is hidden until the next update, which will improve the reliability of rank detection.

**Comment by stevschmid** [comment]
Will update #112 when this is adressed.
