### ISSUE TITLE
Cards, created by another cards, reduce deck detection accuracy

### ISSUE THREAD

**Issue by LinogeFly** [stevschmid/track-o-bot#118]
Hello,

I'm not sure if someone already reported about this but I checked all open issues and didn't find any. The problem is cards. that were created by another cards. mess up proper deck detection. For example, I don't have Flame Imp or Abusive Sargent in my warlock deck. But I get those from Dark Peddler and play them during the game. As a result my deck gets identified as Zoolock quite often which is not the case. It started to be a problem now because of new Discover mechanics. There are more ways now to generate cards that are not in your deck.

Probably it's possible to exclude "Created by" type of cards from deck detection logic. Would be great if you would add this feature at some point in the future.

And thanks for the great tool :)

**Comment by stevschmid** [comment]
That is a good point. Thanks for the report. I'll try to address this in the upcoming version.

**Comment by stevschmid** [comment]
I added some fixes related to the detection of the `cards played`-feature starting with 0.7.x. Check out the upcoming 0.7.1 (soon in the auto-update queue) if this issue still persists.
