### ISSUE TITLE
Invalid ordering in game history

### ISSUE THREAD

**Issue by denton** [stevschmid/track-o-bot#119]
In game history my opponent's turn 5 incorrectly recorded as turn 6 move (opponent conceded on turn 6). Screenshot:
![ordering_error](https://cloud.githubusercontent.com/assets/110861/11629168/9b6ac49a-9d07-11e5-9b4a-d52be8a232a5.png)

**Comment by stevschmid** [comment]
Please reopen if it still persists with 0.7.1 (will be added to auto-update queue soon).
