### ISSUE TITLE
Separate flagging for challenge mode

### ISSUE THREAD

**Issue by JustinasDaugela** [stevschmid/track-o-bot#124]
Hi, I have no idea whether that's possible from the client side, but having games played in challenge mode tracked separately would be very convenient. I play some online tournaments and since decks there are way different from ranked play, it would be great to be able to see those stats separately.

If such a flag would exist, I could do some work on the website to implement a separate section, or even make a detection for BO3/BO5 matches (pretty simple - you play a 'friendly challenge' vs the same person for >=2 or >=3 games). They could also be set automatically, or set manually in the website if you don't find that convenient.

**Comment by stevschmid** [comment]
What is the challenge mode? Do you mean friendly mode where somebody on your friendlist challenges you to a duel? Well you can filter the stats and history by "friendly". More than that (e.g. BO detection) is beyond the scope of Track-o-Bot, but is possible via the API.
