### ISSUE TITLE
Class Stats - Custom timerange Timestamp issue 

### ISSUE THREAD

**Issue by phantomlorenz** [stevschmid/track-o-bot#126]
Not sure whether I need to configure my timezone specifally, but seems that class stats is not correct, see attached files for explanation, I had 3 win vs warlock on 2016-01-03 (2016-01-03T14:39:36.267Z" in the profile.json), but class stats with custom time range from 2016-01-01 to 2016-01-03 is not showing the warlock wins, if I modify the query string manually to be 2016-01-01 to 2016-01-04 then it would show properly, my local cloak is GMT+8, using Mac OS X 10.11.2 if that is any help 

![3 warlock win on 2016-01-03](https://cloud.githubusercontent.com/assets/1845992/12079273/af0f819a-b26d-11e5-9b47-370bf51d3428.png)
![class stats from 2016-01-01 to 2016-01-03](https://cloud.githubusercontent.com/assets/1845992/12079272/af0d8886-b26d-11e5-9380-14bd29970c59.png)
![class stats from 2016-01-01 to 2016-01-04](https://cloud.githubusercontent.com/assets/1845992/12079271/af0be3b4-b26d-11e5-89e4-0e836795ee47.png)

[profile.json.txt](https://github.com/stevschmid/track-o-bot/files/76632/profile.json.txt)

**Comment by stevschmid** [comment]
Custom Time Ranges do not respect your local time zone.
