### ISSUE TITLE
Updating games in the history shows decks for the wrong classes

### ISSUE THREAD

**Issue by AlmostMatt** [stevschmid/track-o-bot#128]
In the game history it is possible to select a match and change what decks were played.

However, even if I played a Mage deck, it lists every deck for every class, in the order of deck creation, instead of just listing the Mage decks. I've never seen trackobot misidentify the class that is played, so don't think that's a valid use case.

If for some reason decks for every class need to be shown, then the decks should be sorted by class instead of sorted by creation order.

**Comment by stevschmid** [comment]
I'm planning on revamping the whole deck system on the website.
