### ISSUE TITLE
Record stats for only a specific account

### ISSUE THREAD

**Issue by jacwah** [stevschmid/track-o-bot#129]
Sometimes my girlfriend comes over and plays Hearthstone on my computer on her account. I always forget to either turn Track-o-bot off or turn it on again afterwards, causing matches not played by me to be recorded, or games actually played by me to be lost. There's no option to remove logged games, so I can't edit the history either.

A setting to only log games played on a specified account would solve my problem. Is this possible?

Thanks for making this tool, it's been a great help for me.

**Comment by AlmostMatt** [comment]
There is actually a hidden feature to manually remove games. On the far right side of each row is a checkmark when you hover over the row, and after you select some games a delete button appears.

**Comment by stevschmid** [comment]
@AlmostMatt is right. Although it shouldn't be a hidden feature, more like an unobtrusive option to remove games :)

**Comment by jacwah** [comment]
I never realized that feature was already there! Thanks @AlmostMatt @stevschmid
