### ISSUE TITLE
Problem uploading results

### ISSUE THREAD

**Issue by stevenle** [stevschmid/track-o-bot#131]
Was there a new release recently? The website is working but results aren't uploading for me lately. Here's the logs:

```
[20:39:56] INFO: Hearthstone is running
[20:46:17] INFO: Result: ranked victory vs. mage as priest. Went second
[20:46:17] INFO: Found an old result. Uploading that first...
[20:46:17] ERROR: There was a problem uploading the result (Code 0). Will save the result locally and try again later.
```

**Comment by stevschmid** [comment]
There was an update to 0.7.1, but it shouldn't have any effect on the upload process. I haven't heard of your issue before. It seems Track-o-Bot is unable to connect to trackobot.com. Did you change anything on your side? What OS are you on?

**Comment by stevenle** [comment]
Odd I tried again this morning and all the backlogged results uploaded. Guess it was a temporary hiccup on my end.

**Comment by jacwah** [comment]
I'm having the same issue as @stevenle. What did you do to solve it? I recognize the log message you posted, and now after I restared Track-o-bot, this is what my log looks like:

```
[20:10:11] INFO: Watching HS logs at /Applications/Hearthstone/Logs
[20:10:12] INFO: 15 unsaved results found
[20:10:12] INFO: Launch v0.7.1 on 2016-02-12
[20:10:12] INFO: Account empty-lightwell-4656 found
```

**Comment by stevschmid** [comment]
Let it run for a bit. It would eventually try to upload the unsaved results.

**Comment by stevenle** [comment]
FYI, I'm seeing this issue again yesterday and today. Tried restarting trackobot but issue persists. Is there a file I can see more detailed logs? I'm on a Mac.

**Comment by stevschmid** [comment]
It's really odd. I only have a limited number of reports with the same [issue] (https://www.reddit.com/r/trackobot/comments/45wlm6/just_noticed_my_arena_didnt_upload_and_im_getting/). Maybe related to Qt. Do you know your way around compiling stuff on Mac? You could try to build it yourself. The instructions are in the README.
