### ISSUE TITLE
Intermittent buzzing sound with headphones, El Capitan

### ISSUE THREAD

**Issue by chanjohnathan** [stevschmid/track-o-bot#132]
After upgrading to El Capitan 10.11.3, I noticed an intermittent buzzing sound (around every 10 secs) when I kept my headphones on with the audio jack in idle mode. After some deep troubleshooting, I pinpointed that this sound stops when I close Track-o-bot and starts when I open it back up again.

**Comment by stevschmid** [comment]
Do you still experience this issue? Track-o-Bot does not use any audio API, so I have no idea why you might experience such an issue.

**Comment by stevschmid** [comment]
I will close this for now. Please reopen if the issue re-appears.
