### ISSUE TITLE
opens up when hearthstone opens

### ISSUE THREAD

**Issue by 2019ygao** [stevschmid/track-o-bot#133]
Starting at login is kind of unnecessary, people doesn't play hearthstone the moment they start up their computer most of the time, so it might a be waste of ram for people that has bad computer.

**Comment by jacwah** [comment]
Track-o-bot currently uses 18.2 MB on my MacBook Air. That's about 0.4% of the 4 GB memory on my laptop. Your suggested change would not make any difference on this front.

Aside from that, there's no way as far as I'm aware to make Hearthstone start and stop third party software. The closest I can come up with is you creating a script or shortcut to launch both in one click. There might also be some kind of process watcher for your operating system that can start and stop processes based on which other processes are running, though I doubt they'd use considerably less resources than Track-o-bot already does.

(Disclaimer: I don't represent Track-o-bot so go to @stevschmid for a definitive answer)

**Comment by stevschmid** [comment]
You can either opt-in or opt-out of starting the app upon login (in the settings). And @jacwah is right: Track-o-Bot is sleek.
