### ISSUE TITLE
Webhook upon events

### ISSUE THREAD

**Issue by pajlada** [stevschmid/track-o-bot#134]
Would there be any interest for the main project to have some webhook events fire off when certain things occur, like when a game starts or so?

Just polling the general interest of it, I'll probably do it regardless but it would be cool to know whether you'd be interested in the feature or not

**Comment by stevschmid** [comment]
I don't see the benefit for the majority of users. But the source code is pretty straight forward. I'm sure you can add callbacks for the events you like.
