### ISSUE TITLE
Record game logs?

### ISSUE THREAD

**Issue by sebastientromp** [stevschmid/track-o-bot#135]
Hello,

I was wondering if Track-o-bot allowed you to save the logs of a game to a separate folder / zip file. I didn't find anything like that in the description.

Is this feature supported?

Thanks!

**Comment by stevschmid** [comment]
The HS game logs can be found in the `Logs` folder in the Hearthstone directory.

**Comment by sebastientromp** [comment]
Does that mean that if I play 10 games in a row, I'll be able to get a file with the logs for each individual game?

**Comment by stevschmid** [comment]
No, you have to process the log files yourself. All the data Track-o-Bot keeps track of can be accessed later via the [web API](https://gist.github.com/stevschmid/120adcbc5f1f7cb31bc5).
