### ISSUE TITLE
Rank 10 icon instead of rank 16

### ISSUE THREAD

**Issue by BriceMortier** [stevschmid/track-o-bot#136]
Hi,

There is a small issue in history records for ranked games: rank 10 icon is displayed instead of rank 16 icon. Here is a screen capture:
![trackobot](https://cloud.githubusercontent.com/assets/17588829/13455149/e419a61a-e05b-11e5-8ad0-a1a223bc4136.png)

Regards,
Brice

**Comment by rmahy** [comment]
I have issue with rank 8 instead of 2, 9 instead of 6.

Also don't understand some reversal like 1st play rank 5, second rank 8 and third rank 4. 
Another exemple : 5 8 10 5.

Robin

**Comment by stevschmid** [comment]
Are you on 0.7.1?

**Comment by rmahy** [comment]
0.7.0
Is it the cause ?

2016-03-02 22:42 GMT+01:00 Steven Schmid <notifications@github.com>:

> Are you on 0.7.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevschmid/track-o-bot/issues/136#issuecomment-191445811>
> .
>



-- 


*Robin Mahy**Ingénieur d'études et développement*


[image: http://www.nextoo.fr/] <http://nextoo.fr>

Immeuble Interligne - 15 Boulevard du Général Leclerc - 59100 ROUBAIX

Tél : 03 28 04 30 85

*Pensez à nos forêts avant d'imprimer ce message*

**Comment by stevschmid** [comment]
Switch to 0.7.1. The rank detection was overhauled tremendously.

**Comment by BriceMortier** [comment]
My Track-o-Bot was indeed not up to date and I just upgraded to 0.7.1. I actually thought that was only a display issue in web app.

**Comment by stevschmid** [comment]
Rank detection in the old version is unreliable.
