### ISSUE TITLE
Ability to export profile via command line (or a log file)

### ISSUE THREAD

**Issue by Muntsinger** [stevschmid/track-o-bot#138]
When using Track-o-Bot through Wine, there is no way to access the context menu.

It would be convenient to be able to export the user profile using some other method (especially now that the Linux fork has received more love).

**Comment by stevschmid** [comment]
The linux fork has an issue section: https://github.com/BOSSoNe0013/track-o-bot

**Comment by Muntsinger** [comment]
This has nothing to do with the Linux fork.

**Comment by stevschmid** [comment]
I still don't understand the request. How are you using Track-o-Bot without the context menu at all?

**Comment by Muntsinger** [comment]
Not sure how/why people would use the context menu.  I just start Track-o-Bot and it runs in the background.  Then after any completed games, they show up on the trackobot.com website.  That's it.

The problem now is that I would like to export my profile to be able to use it with the Linux version (where hopefully I can access the context menu) or even for backup purposes.  Is there any way to get this outside of the context menu?

**Comment by theanine** [comment]
Any word on this?  I would really like to export my profile somehow.

**Comment by stevschmid** [comment]
Can you access the [icon](https://trackobot.com/assets/step_profile-8627f83b36d89a7460e3999514d75f80.png)? The UI of Track-o-Bot is only accessible via this tray icon. 

If you only need the profile, you could get your account info from the preferences file (no idea where Wine saves them), install the Linux version, and manually edit the preferences file from the latter (overriding the account information). That is equal to how the account export/import works.

**Comment by theanine** [comment]
Where does the preferences file get saved on Windows?  Wine just uses the same path that Windows does, except stores it in your Linux home dir under: `~/.wine/drive_c/`

**Comment by stevschmid** [comment]
`%LOCALAPPDATA%/spidy.ch/Track-o-Bot`

**Comment by theanine** [comment]
The only thing I see in that path is the log.  There are no other files there.

**Comment by stevschmid** [comment]
It seems I cannot help you, sorry. I never used Wine and I cannot support any OS besides Windows 7+ and OS X 10.9+

**Comment by theanine** [comment]
Can you tell me the name of the file?  Pretty easy to search for it, if I have the name.

**Comment by stevschmid** [comment]
Actually the credentials are stored in the Windows registry if I recall correctly . 
`HKEY_CURRENT_USER/SOFTWARE/spidy.ch/Track-o-Bot`
