### ISSUE TITLE
Trigger upload manually

### ISSUE THREAD

**Issue by jacwah** [stevschmid/track-o-bot#141]
Sometimes I open up my Track-o-Bot profile after a suite of games only to find that none of them had been uploaded. I proceed to check the log where I'm met by a row of "There was a problem uploading the result. Will save the result locally and try again later." That is when I think "But I want to see my stats now!!!" (without playing another game). After restarting Track-o-Bot these uploading issues usually resolves.

For these kind of situations, which occur quite frequently for me, I suggest a "Upload backlog" button under the settings menu. Pressing this button would manually trigger an upload to be started and after #139 is resolved all results can be swiftly uploaded.

**Comment by stevschmid** [comment]
"There was a problem uploading the result" should never occur under normal circumstances. The new version will improve the upload process.
