### ISSUE TITLE
fix for possible crash in QCoreApplication::arguments()

### ISSUE THREAD

**Issue by angrylinuxuser** [stevschmid/track-o-bot#142]
Hi,
In linux fork there is a fix that fixes QCoreApplication::arguments() crash that i think is not platform specific.
For me it manifests when compiling trackobot with clang.
Here is a link: https://github.com/BOSSoNe0013/track-o-bot/commit/db418aaedd86b2f911d26c1c6c5bef6bb74d7512

Its based on last comment in this: https://bugreports.qt.io/browse/QTBUG-5637

**Comment by stevschmid** [comment]
Thanks for the report.
