### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Greyvend** [stevschmid/track-o-bot#148]
It's be nice to have the Linux version of the app. Since it's Qt based I guess one can try compiling on Linux? Has anyone tried? Or maybe there is a way to install using wine? If the tweaking not that complicated I'd be glad to help.

**Comment by angrylinuxuser** [comment]
there is a fork: https://github.com/BOSSoNe0013/track-o-bot/commits/master

**Comment by stevschmid** [comment]
Please check out the linux fork which @angrylinuxuser mentioned.
