### ISSUE TITLE
log.config rewriting breaks having both track-o-bot and ArenaTracker running together

### ISSUE THREAD

**Issue by soli** [stevschmid/track-o-bot#149]
Hi,

thanks a lot for track-o-bot, I'm really happy with it as a statistics tracker for HS. However for other purposes I also like https://github.com/supertriodo/Arena-Tracker/ and this creates an issue…

Indeed, I need to get a `log.config` that makes both happy, which is possible (https://github.com/supertriodo/Arena-Tracker/issues/11) but unfortunately gets broken each time I (re)start track-o-bot [the rewriting of regexps actually leads to duplicate lines].

Would it be possible to change the `log.config` handling in such a way that `FileLogging=false` gets rewritten or added, but not `ConsoleLogging=true`?

Thanks.

**Comment by soli** [comment]
Cc @supertriodo

**Comment by stevschmid** [comment]
The rewrite is/was necessary because older versions of Track-o-Bot would use ConsoleLogging and that caused lags for some users.  The author in the linked issue is now using `FileLogging`, which is the preferred method.
