### ISSUE TITLE
Idea: detect and store region

### ISSUE THREAD

**Issue by mislav** [stevschmid/track-o-bot#166]
For the purpose of long-term collection and analysis of gameplay data, it might be a good idea to store the active region (if possible) with other data. For now, this information doesn't have to be exposed in any way on the site, but just having the data could be useful in the long run.

**Comment by stevschmid** [comment]
That was implemented in the most recent version of the client. I still have to implement it on the server side: https://github.com/stevschmid/trackobot.com/issues/66

**Comment by mislav** [comment]
Good news! Thanks!
