### ISSUE TITLE
Incorrect stats in custom period including current day

### ISSUE THREAD

**Issue by darksteel88** [stevschmid/track-o-bot#167]
When you make a custom period to check stats with, games from the current day are not correctly populated. I have an example below. You can see it shows me being 3-0 vs Aggro Shaman in the last 24 hours, but shows me having 1 win against them in the custom period. The custom period includes today's date, as of this post. Not sure what's going on but something's not right.

![cthunwarriorcustom](https://cloud.githubusercontent.com/assets/2425705/16550166/164fcffe-4175-11e6-80f7-0d3030c02352.png)
![cthunwarriorlast24](https://cloud.githubusercontent.com/assets/2425705/16550170/20cdd30e-4175-11e6-9c79-b9c563e75552.png)

**Comment by stevschmid** [comment]
It does not respect your local time zone. I'll eventually add a time zone option in the profile.
