### ISSUE TITLE
Add games from UI

### ISSUE THREAD

**Issue by RNiveau** [stevschmid/track-o-bot#177]
It could be great to add games from UI.
When you play with smartphone or ipad, you lost stats about winrate for example and it's frustrating.

**Comment by LesnikovPavel** [comment]
You can use this page: http://hearthstonehelper.azurewebsites.net/Trackobot/AddGame

**Comment by RNiveau** [comment]
Thanks for this page.

May be you should be a link from https://trackobot.com :)

**Comment by stevschmid** [comment]
Some people are also working on mobile apps and such, so I think there are (external) options to add games without making the web UI too complex.
