### ISSUE TITLE
incorrect rank recorded

### ISSUE THREAD

**Issue by rrwoods** [stevschmid/track-o-bot#178]
I just played my first game of the new season.  The game was played at rank 19, but my Track-O-Bot profile shows it as a rank 4 game.

The ID of the game according to the JSON is 36584345.

EDIT: The next three games also exhibited this issue,  Their JSON IDs were
36586830
36586477
36585437

**Comment by Phaton** [comment]
The program is recording the rank propertly of the games I play with my alternate account (ranks 20 to 16) but not the games I play with my main account (ranks 5 to 3)
JSON ID of not recorded games: 
38041503
38040390
38040863

**Comment by stevschmid** [comment]
See #181
