### ISSUE TITLE
Unable to set password on the website?

### ISSUE THREAD

**Issue by darthdeus** [stevschmid/track-o-bot#179]
I get automatically logged in, but if I access the site from a different computer, it requires login/password, which doesn't seem to be possible to set anywhere.

**Comment by rjhilgefort** [comment]
I believe the process is to export (from your first computer), then import your profile on whatever other computer you want. Untested- but that's what I gathered from the docs.

**Comment by stevschmid** [comment]
@rjhilgefort is right.
