### ISSUE TITLE
Add Malygos Druid & Beast Druid

### ISSUE THREAD

**Issue by darthdeus** [stevschmid/track-o-bot#180]
Since there's already Malygos Rogue, it would be nice if there also was Malygos Druid ... they're imho about the same popularity.

Another archetype that's already becoming popular, and most likely will storm the ladder next week when menagerie opens, is the Beast Druid.

**Comment by stevschmid** [comment]
Please use the official subreddit r/trackobot to post ideas about new archetypes.
