### ISSUE TITLE
Plugin support?

### ISSUE THREAD

**Issue by ttvd** [stevschmid/track-o-bot#203]
Hi!

Firstly, thanks for writing an awesome and useful tool. I use it on a regular basis now.

I am interested in collecting data for a personal statistical analysis project. And I am wondering if there's a plan to add a plugin support to track-o-bot, so I could write a stats collecting plugin? I could patch the code and run a fork, but it seems like a wrong way to do it and I need to run it on multiple machines.

Thanks!

**Comment by stevschmid** [comment]
trackobot.com offers a web API (https://gist.github.com/stevschmid/120adcbc5f1f7cb31bc5)

**Comment by ttvd** [comment]
We are not really interested in using the web end.

**Comment by stevschmid** [comment]
I am not really interested in adding plugin support.

**Comment by ttvd** [comment]
I thought about doing this work and merging back into your project, but that does it then. Thanks.
