### ISSUE TITLE
Multiple mini pie-chart

### ISSUE THREAD

**Issue by andybergon** [stevschmid/track-o-bot#205]
Going in Deck matchups details and returning back create another mini pie-chart. Here's a screenshot.
![2017-02-06 02_01_25-deck stats - track-o-bot](https://cloud.githubusercontent.com/assets/5220825/22631583/5e9f16b6-ec10-11e6-8614-93dc70ab03e0.png)

**Comment by stevschmid** [comment]
Thanks for the report. Probably a problem with turbolinks. I'll fix it in the next version.
