### ISSUE TITLE
add new deck type

### ISSUE THREAD

**Issue by donaldtse118** [stevschmid/track-o-bot#207]
currently manual edit of deck type detection is limited. 

e.g. rogue, we got miracle rogue, jade rogue and other rogue
suggested to add more type to catch up with meta ( detection may not work yet, but at least user can manual select from the list ) ..generic type can be added : aggro , midrange, control..

free text may not a good idea to manage...and i think you already the option 'other' already serve this purpose.

i'm pull the source but i did not find code that classifier deck ...is it in another source? or can you enlighten me, thanks

**Comment by stevschmid** [comment]
https://github.com/stevschmid/trackobot.com

Decks will get updated soon(TM).
