### ISSUE TITLE
Memory leak ( possible false positive )

### ISSUE THREAD

**Issue by angrylinuxuser** [stevschmid/track-o-bot#209]
Hi, i used valgrind memory analyzer to analyze ToB and i found one definite memleak in Window::CreateTrayIcon() on line:161 mTrayIcon->setContextMenu ( mTrayIconMenu ); 
On windows side ( via virtualbox ) i runned drmemory and it reported it as possible memleak

Its a strange since every thing here has a parent so it might be a false positive.
However i found this: https://forum.qt.io/topic/75820/memory-leak-using-qsystemtrayicon/4

And based on that comment i created a fix which ill submit in a pull request

**Comment by stevschmid** [comment]
Thanks for the PR. I will consider it for an upcoming update. Worst decision during development of Track-o-Bot was definitely to opt for Qt. Never again...
