### ISSUE TITLE
Disable overlay

### ISSUE THREAD

**Issue by fcasco** [stevschmid/track-o-bot#212]
I installed it on Linux using the fork but when I open Hearthstone I get a black overlay which prevents me from using the game. I just want to track my actions, is there a way to disable the overlay?

**Comment by angrylinuxuser** [comment]
Overlay is black because You are using non-composited wm-manager. You can
disable in Settings tab ( tob icon is in system tray)

2017-04-11 3:39 GMT+02:00 Facundo <notifications@github.com>:

**Comment by stevschmid** [comment]
Linux is not officially supported. Please post the issue in the fork repo.
