### ISSUE TITLE
Can we have custom decks for tracking back?

### ISSUE THREAD

**Issue by darksteel88** [stevschmid/track-o-bot#214]
I've found that the automated deck tracking isn't the best system. It has always been a bit of a problem that it limited deck classification, but right now the fact that it hasn't been updated is proving to be a bigger issue.

It has been 10 days since the release of the set and so far there's no tracking for deck archetypes other than what previously existed. Several decks fail to classify themselves, making it difficult to look at stats at a glance. 

I would much prefer to just manually add the different classifications myself like we used to.

If not, can we at least get some updated deck detection? It doesn't seem to me like it's a big deal to do, if adding archetypes is anything like the old interface was, it should really only take a few minutes.

**Comment by stevschmid** [comment]
Decks will get updated when the meta is somewhat settled. Custom deck tracking might come back in the future.
