### ISSUE TITLE
Share your data please

### ISSUE THREAD

**Issue by Sammers21** [stevschmid/track-o-bot#219]
You have a backend server with all data about games tack-o-bot users play.

So, I would like to analyze them. Can you provide usernames and tokens?

**Comment by Michelemassari** [comment]
Is this supposed to be a joke? No-one in the right state of mind would give away username and private tokens of their users.

**Comment by Sammers21** [comment]
@Michelemassari, is this information is really private? to be clear it is even anonymized

**Comment by Michelemassari** [comment]
It is, as I'm fairly sure that having usernames and token would allow you to use the API as them
