### ISSUE TITLE
after update 9.2, ranked games are recorded as casual

### ISSUE THREAD

**Issue by gabbayo** [stevschmid/track-o-bot#222]
After I installed update 9.2 to HS, all my ranked games appear as casual in my profile.
I use Win10 and my TOB version is 0.8.7

**Comment by pickymiki** [comment]
I have the same issue. Ranked games are recorded as casual. I'm on MacOS 10.12.6 my TOB version is 0.8.6

**Comment by RRReDz** [comment]
Same issue for me!

**Comment by sdc111** [comment]
u/triodo, Arena Tracker maintainer, noted that 9.2 introduced a logfile format change. Arena Tracker uses the same db as Track-o-Bot. guessing that Track-o-Bot just needs a similar update.

**Comment by SteveRodrigue** [comment]
Exact same issue here.

**Comment by stevschmid** [comment]
Thanks! I hope to find some time to fix this soon(TM).

**Comment by geratheon** [comment]
I just researched a little bit by looking at logfiles and the code of Arena Tracker (as mentioned above) and I fixed it. I'd love to see the pull request merged and a new release rolling out soon, since not everyone might be in the position of making a build for himself.

**Comment by gabbayo** [comment]
geratheon, any chance you can create a release in your fork so ordinary people can download and install ?

**Comment by geratheon** [comment]
Unfortunately, I don't have the disk space for QT available on my Windows PC, so I can just supply you with a macOS Application.
