### ISSUE TITLE
Since witchwood, turns played are not displayed in the history pages

### ISSUE THREAD

**Issue by ShereKahn** [stevschmid/track-o-bot#228]
Since the witchwood extensions, games where witchwood cards have been played are not displaying a pre/turn based summary when hovering over the crossed sword icons.

**Comment by stevschmid** [comment]
Thanks for the report. Can you please check again if the cards show up for **new** matches? (new = from now on)

**Comment by ShereKahn** [comment]
Hello Steve, 

They actually don't. 

I am running track-o-bot 0.9.0, and did a couple of games right now, the cards are still not showing up. Let me know if you need my track-o-bot id for troubleshooting purposes.

Thanks 
Alain

**Comment by ShereKahn** [comment]
My bad, they actually show up. I still had a filter set ... 

Seems the issue is solved ! Thanks !
