### ISSUE TITLE
Change website username/password?

### ISSUE THREAD

**Issue by kennonlee** [stevschmid/track-o-bot#37]
Sorry to bother you with a trivial issue, but I wasnt sure where else to ask. I'd like to be able to log into my online account from a different computer. How can I set/change my password to do this? It would be nice to be able to change username as well, though this isn't too important.

I can get to some pages by pasting in my username and token as url vars, but this wont work on POSTs (e.g., to edit cards in decks).

**Comment by zwerch** [comment]
I have the same possibly trivial issue. I'm tracking my games with HSTracker and uploading them on Track-o-Bot automatically. Now I would like to see my game history on track-o-bot.com without always having to start the tool so I can also access it on my phone / tablet etc.
Where do I find my login credentials / where can I reset them? The export file seems to be hashed / encrypted somehow, at least I can't find a working password in there. I'd really appreciate some help regarding this.
