### ISSUE TITLE
Two games combined into one after disconnect

### ISSUE THREAD

**Issue by robro** [stevschmid/track-o-bot#55]
I experienced a disconnect at the end of a Priest mirror, in which I won, and got the "Game completed and recorded. Please restart Hearthstone to continue." message. After restarting I checked my track-o-bot profile to see that the game had not been recorded by the app.

I then played another game, this time as Warrior, against another Priest. I won that game as well and upon checking my profile again I saw the Warrior game listed but when I checked the cards played I saw that it listed both the cards played during the Warrior game as well as the Priest game.

See attached image:

![trackobot_combinedgames1](https://cloud.githubusercontent.com/assets/433665/4873717/67a112c6-6221-11e4-98f2-84e3602eb902.png)

I then checked the match history and saw that the plays from both games had been combined into one.

See attached image:

![trackobot_combinedgames2](https://cloud.githubusercontent.com/assets/433665/4873718/710a4d0a-6221-11e4-953f-1cd1f1ba28f6.png)

I will e-mail the output_log to you.

**Comment by stevschmid** [comment]
Please reopen the issue if this still occurs.
