### ISSUE TITLE
Problem tracking

### ISSUE THREAD

**Issue by barisdemiroz** [stevschmid/track-o-bot#59]
I am having problems tracking my games on two different computers. Track-o-bot log says "Hearthstone found." and doesn't react to anything.

Both machines are running Windows 7. There is one common thing with them: I have copied Hearthstone folder and Battle.net client folder to both machines, then I manually located the Hearthstone folder inside Battle.net client. I am suspecting this might be the cause.

I checked if Hearthstone is producing logs, it is working fine. Another Card tracker program works fine using it.

What else can I do to pinpoint the error to find the root cause? How can I fix it?

**Comment by Ischafak** [comment]
Baris nasıl düzelttin kardeşim ?

**Comment by stevschmid** [comment]
@Ischafak can you formulate your question in english?

**Comment by Ischafak** [comment]
Ok i dont understand this problem i cant fix it can you help me ?

**Comment by Ischafak** [comment]
Now i trying scan and repair

**Comment by Ischafak** [comment]
only it said [00:18:04] Account young-kidnapper-9386 found
[00:20:04] Hearthstone found
[00:26:21] Hearthstone was closed
[00:27:52] Hearthstone found and my history is empty

**Comment by stevschmid** [comment]
Try to click the button in your Battle.net launcher on the image above -> https://trackobot.com/assets/faq_scanrepair-81d39daff810fca86c6edb11f2095096.jpg

Then restart the game and Track-o-Bot!

**Comment by pencil** [comment]
What button?

**Comment by Ischafak** [comment]
it works thx rly :D

**Comment by stevschmid** [comment]
Glad to hear!

And @pencil I hope you'll find the button one day :opieop:

**Comment by Ischafak** [comment]
ashdahah
