### ISSUE TITLE
Unable to open Track-o-Bot on OSX Yosemite 10.10

### ISSUE THREAD

**Issue by nikhdpro** [stevschmid/track-o-bot#64]
Hey Steve,

I'm unable to open Track-o-Bot on Yosemite. Nothing launches after I open it. There is no feedback form the OS, no crash report window.

I did generate a crash report from Console, hope it helps...

[Track-o-Bot_2014-12-05-125303.crash] (http://cl.ly/3E003b0F0M3I) 
[Crash logs.log] (http://cl.ly/0H3F2V0R3f1N)

**Comment by stevschmid** [comment]
Should be fixed.
