### ISSUE TITLE
Request: Remove specific matches/arenas

### ISSUE THREAD

**Issue by feffocalen** [stevschmid/track-o-bot#65]
Just that, a simple X in each match/arena row would be perfect. It could only appear when hovering the row to maintain the interface clean. and maybe an undo link in the notification after the removal.

![capture](https://cloud.githubusercontent.com/assets/7383708/5327910/7993dd22-7d44-11e4-9157-d34c4ed1580a.PNG)

It's a nice way to delete:
* matches that we're added while spectating someone.
* arenas that were uplodaded with errors.
* auto concedes (like the one in the capture).
* disconnects.
* unwanted matches/arenas.
* every match/arena for an account cleanup.

I would try to do it myself but i don't know any of ruby/cpp :(

**Comment by gssjr** [comment]
I'm developing this feature. Thanks to @bergren2 for linking the issue

**Comment by stevschmid** [comment]
Track this in the trackobot.com Repo
