### ISSUE TITLE
Arena stats being calculated incorrectly

### ISSUE THREAD

**Issue by nickelization** [stevschmid/track-o-bot#66]
Noticed an issue today looking at my Arena Stats page. It somehow hasn't registered my Warrior run as completed, even though I've lost three games and done two other arena runs since then. It also appears to be calculating "wins on average" as (7+7+9)/2 instead of (7+7+9)/3 like it should. Screenshot:

![screen shot 2014-12-13 at 3 40 34 pm](https://cloud.githubusercontent.com/assets/4108538/5425302/0a368ccc-82df-11e4-97d8-8a6fe3e812c7.png)

Log: https://gist.github.com/nickelization/84a540a85526b84fdc22

I'm running the Mac version of the client, version 0.4.2. If you'd like any other info, let me know!

**Comment by stevschmid** [comment]
Can you send me your username?

**Comment by nickelization** [comment]
Hi there, sorry for the slow reply, I didn't notice your latest comment until now. I don't want to post my username publicly so I'm sending you an email with the info. Thanks - Nick

**Comment by stevschmid** [comment]
Continued in https://github.com/stevschmid/trackobot.com/issues/44
