### ISSUE TITLE
Own Class Unknown

### ISSUE THREAD

**Issue by pewsey** [stevschmid/track-o-bot#67]
From the logfile
[21:01:17] Hearthstone found
[21:17:32] Upload ranked victory vs. warlock as priest. Went second
[21:17:35] Result was uploaded successfully!
[21:23:26] Upload ranked defeat vs. hunter as priest. Went second
[21:23:29] Result was uploaded successfully!
[21:32:43] Own Class unknown. Skip result
[21:32:49] Hearthstone was closed

I played 3 games for my daily quests using my priest.

First game vs warlock I thoughtstole Juraxxus and won the game - it appears to be recorded correctly
Second game I got rushed down by a hunter - recorded correctly
Third game I beat an aggro hunter - the "Own class unknown" message and the result not known.

It would be great to have an ability to a) remove games and b) add in "results" for issues like this. I'm not super competitive, but having the ability to reasonably accurately record the results (without the card play) would be good.

Also, under circumstances like this - it would be very valuable to write the a "failed result" logfile to the track-o-bot directory, so we could potentially assist with debugging, or even "re-submit" the logfile to the server so we don't lose data. 

Losing information makes me sad.

**Comment by stevschmid** [comment]
Please reopen the issue if this still persists.
