### ISSUE TITLE
Deck vs Class

### ISSUE THREAD

**Issue by howardjohn** [stevschmid/track-o-bot#73]
Would it be possible to be able to view the stats on my decks vs other classes? I don't have every deck saved as decks so when I am trying to see my match up as a certain deck against other classes I can only see it against decks I have defined.

**Comment by ktrain** [comment]
Track-o-bot can only see the cards that you play, not the deck that you've selected. It determines what deck you're playing by matching up the cards that you play with the cards that you've chosen to that define and characterize the deck.

**Comment by Kironide** [comment]
What I mean by this is that on the website you can view class vs class stats or deck vs deck stats. I want to be able to view deck vs class stats.

**Comment by ktrain** [comment]
Ah true, good point.

**Comment by stevschmid** [comment]
No plans in the immediate future to add this. Would be a helpful addition though.

**Comment by stevschmid** [comment]
I will close this issue for now, but keep this in mind for the future.
