### ISSUE TITLE
Games submitted twice

### ISSUE THREAD

**Issue by thrar** [stevschmid/track-o-bot#76]
For some reason I had two instances of Track-o-Bot running while I was playing. As a result, both instances reported my games, so that every game I played today shows up twice.
My account as shown in the bot is `delicate-shieldbearer-8302`.

Is it possible to ensure only one instance is running? I'm on Windows 7 and have it configured to run on startup. `msconfig` shows it only once, so I don't know where my second instance might have come from.

If that's not viable, maybe there's a way to detect duplicates on the server? Would it be possible to go by timestamp (could be exact time, since they're simultaneous)?

Finally, is there a way for me to delete the duplicate games from my history?

**Comment by stevschmid** [comment]
Normally Track-o-Bot prevents two instances. I'm not sure what happened in your case. Please reopen this issue if it happens again.

There is no way at the moment to delete games I'm afraid.

**Comment by thrar** [comment]
I got two instances again today. I can't start it twice manually (as intended), but I'm getting two instances started automatically when Windows starts.
Looks like it's reproducible; I tried restarting the computer just now and once again ended up with two instances.

**Comment by thrar** [comment]
I tried disabling the autostart option and restarted, that worked as expected (i.e. the bot didn't start).
After that, I enabled autostart again and once more restarted the computer. This time I only got one instance.

Looks like I don't have the rights to reopen the issue, seems only contributors can do that.

**Comment by stevschmid** [comment]
But it's fixed for you now? I never heard about this problem before.

**Comment by thrar** [comment]
Yes, currently I'm only getting one instance.
