### ISSUE TITLE
[Linux] Trackobot compiles and runs. Can access GUI, but program isn't uploading match results

### ISSUE THREAD

**Issue by gnummers** [stevschmid/track-o-bot#81]
Please see topic/subject. Not sure where to proceed from here? What info would you like on my system?

http://i.imgur.com/gJaayyg.png - Please note that it says Hearthstone found.
http://i.imgur.com/uyGcw1K.png - Clicking check for updates now doesn't seem to do anything.

I'm not getting any error messages at all in terminal. Just some warnings:

gnum@vincent-desktop ~/src/track-o-bot-master/build $ ./Track-o-Bot 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Fontconfig warning: FcPattern object size does not accept value 10(i)
Fontconfig warning: FcPattern object size does not accept value 10(i)
Created new window in existing browser session.
Fontconfig warning: FcPattern object size does not accept value 10(i)
Fontconfig warning: FcPattern object size does not accept value 10(i)
Created new window in existing browser session.
Fontconfig warning: FcPattern object size does not accept value 10(i)
Fontconfig warning: FcPattern object size does not accept value 10(i)
Created new window in existing browser session.
Fontconfig warning: FcPattern object size does not accept value 10(i)
Fontconfig warning: FcPattern object size does not accept value 10(i)
Created new window in existing browser session.
Fontconfig warning: FcPattern object size does not accept value 10(i)
Fontconfig warning: FcPattern object size does not accept value 10(i)
Created new window in existing browser session.

Is this simply a java permissions issue? How can I diagnose this?

gnum@vincent-desktop ~/src/track-o-bot-master/build $ uname -a
Linux vincent-desktop 4.0.4-gentoo #17 SMP PREEMPT Thu Jun 4 17:54:01 EDT 2015 x86_64 Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz GenuineIntel GNU/Linux

Thanks in advance.

Edit: Is it possible I'm missing a dependency somehow?

**Comment by stevschmid** [comment]
Linux is not an officially supported OS.

**Comment by K900** [comment]
I looked into Linux support a bit, and it seems doable without too much extra work. Are you interested in this at all?

**Comment by stevschmid** [comment]
There is already a [fork](https://github.com/BOSSoNe0013/track-o-bot) out there. What I meant is that I can't support any version which is not running on Windows or Mac OS X.

**Comment by gnummers** [comment]
The fork seems to need a bit of maintenance. Sorry, I posted here because the fork is also lacking an issues section.

**Comment by stevschmid** [comment]
I hope he gets a notification about my comment [here](https://github.com/stevschmid/track-o-bot/pull/34#issuecomment-110185237) and will enable issues for the Linux fork. I don't use Linux for desktop and Hearthstone is not supported on said OS.

That being said, I'm happy to see people using the power of open source to modify software to their own needs.

**Comment by gnummers** [comment]
Thanks! He's enabled the issues section and I've posted just now.
