### ISSUE TITLE
Results of the matches with new heroes are not recorded

### ISSUE THREAD

**Issue by aia** [stevschmid/track-o-bot#82]
Matches are not recorded at trackobot.com when playing with a new hero (Magni, Medivh, Alleria) or against a new hero.

[21:04:36] Own Class unknown. Skip result
[21:15:04] Own Class unknown. Skip result
[21:24:49] Own Class unknown. Skip result

**Comment by stevschmid** [comment]
Thanks for the report. Expect a new version soon.

**Comment by aia** [comment]
Here's a patch:

diff --git a/src/HearthstoneLogTracker.cpp b/src/HearthstoneLogTracker.cpp
index ff8fd8a..8eaa3ff 100644
--- a/src/HearthstoneLogTracker.cpp
+++ b/src/HearthstoneLogTracker.cpp
@@ -10,7 +10,7 @@ const char HERO_POWER_CARD_IDS[NUM_HERO_POWER_CARDS][32] = {
 };
 
 // Hero Ids: Must match Class enum
-const int NUM_HEROES = 9;
+const int NUM_HEROES = 12;
 const char HERO_IDS[NUM_HEROES][32] = {
   "HERO_09", // CLASS_PRIEST = 0,
   "HERO_03", // CLASS_ROGUE,
@@ -20,7 +20,10 @@ const char HERO_IDS[NUM_HEROES][32] = {
   "HERO_07", // CLASS_WARLOCK,
   "HERO_05", // CLASS_HUNTER,
   "HERO_02", // CLASS_SHAMAN,
-  "HERO_06" // CLASS_DRUID,
+  "HERO_06", // CLASS_DRUID,
+  "HERO_01a", // CLASS_WARRIOR, Magni
+  "HERO_05a", // CLASS_HUNTER, Alleria
+  "HERO_08a" // CLASS_MAGE, Medivh
 };
 
 Q_DECLARE_METATYPE( ::CardHistoryList );
diff --git a/src/Local.h b/src/Local.h
index a4a217b..d053c32 100644
--- a/src/Local.h
+++ b/src/Local.h
@@ -99,6 +99,9 @@ typedef enum {
   CLASS_HUNTER,
   CLASS_SHAMAN,
   CLASS_DRUID,
+  CLASS_WARRIORA,
+  CLASS_HUNTERA,
+  CLASS_MAGEA,
   CLASS_UNKNOWN
 } Class;
 
@@ -112,10 +115,13 @@ const char CLASS_NAMES[][128] = {
   "hunter",
   "shaman",
   "druid",
+  "warrior",
+  "hunter",
+  "mage",
   "unknown"
 };
 
-#define NUM_CLASSES 9
+#define NUM_CLASSES 12
 
 class CardHistoryItem {
 public:

**Comment by stevschmid** [comment]
Thanks @aia! Much appreciated. I will use a slightly other approach to make sure the unreleased heroes are supported as well.

**Comment by stevschmid** [comment]
Should be fixed in 0.4.7.
