### ISSUE TITLE
Add optional date range for deck specification 

### ISSUE THREAD

**Issue by pewsey** [stevschmid/track-o-bot#83]
I would love the ability to add in a date to decks, as it's getting hard to differentiate some of the newer decks with small changes in them (control warrior, handlock, mid-range paladin) have remained relatively the same from season 9 to season 15 with minor variations.

This makes it really fiddly to try and get the winrates for older decks (and newer decks)

I would like to be able to say "between <date> <date>" as part of the deck information so I can sensibly "archive" old decks. 

It's pretty minor, and I don't know how many other people would use it, but I do love me some stats kept all nice and clean.

Thanks for the great work.

**Comment by narnou** [comment]
Actually this is something that would make me happy too ! :)
I found myself struggling with my too many variations of an hybrid Demonlock/Handlock :(

**Comment by stevschmid** [comment]
This feature was added a couple of weeks ago. Thanks for the suggestion!
