### ISSUE TITLE
Support korean version

### ISSUE THREAD

**Issue by stevschmid** [stevschmid/track-o-bot#84]
For checking whether or not the game is running for korean players, one has to check if a window title is "하스스톤" (in ``WinWindowCapture`` and ``OSXWindowCapture``)

**Comment by clooth** [comment]
Don't you mean Hearthstone.cpp?

**Comment by stevschmid** [comment]
The problem is that the `WindowsCapture` constructor currently only allows one `windowName`, but it should support multiple ones. The korean string itself should be placed in `Hearthstone.cpp`, you are correct.
