### ISSUE TITLE
Support for username change

### ISSUE THREAD

**Issue by ecbrodie** [stevschmid/track-o-bot#85]
There doesn't appear to be support for changing the username generated by default on initial app startup. This seems to be an essential feature for supporting a single account on multiple devices. Is this feature in the works? If not, will you accept pull requests for adding this feature in?

**Comment by stevschmid** [comment]
You can simply export your account credentials via the settings and import it on another device? See the FAQ entry on trackobot.com

**Comment by ecbrodie** [comment]
Then how about support for changing the username from the automatically
generated name? I don't want to be a nameless archmage forever.

**Comment by stevschmid** [comment]
You can change the displayed name on your profile by clicking on it.
