### ISSUE TITLE
Merged "Cards played"

### ISSUE THREAD

**Issue by scott-maddox** [stevschmid/track-o-bot#86]
There's a bug with the "Cards Played" feature. I'm guessing it's an unintentional database merge at some point, or similar. See the image below. There's no way for a shaman to play that many rogue cards. Two matches must have been merged together.

Unfortunately, that's about all the info I have to provide.

![image](https://cloud.githubusercontent.com/assets/3509144/8688431/b1cca5dc-2a61-11e5-9181-63e7f6558945.png)

**Comment by stevschmid** [comment]
Will look into this for the upcoming version. Thanks for the report!

**Comment by stevschmid** [comment]
The new version (0.6.0) should be more reliable in this regard. Reopen the issue if this problem still persists for you.
