### ISSUE TITLE
Friend match logged as Arena run

### ISSUE THREAD

**Issue by denton** [stevschmid/track-o-bot#87]
I just watched my friend ranked play and this was recorded as arena match, so my arena run stats are now broken.
https://trackobot.com/profile/history?arena_id=238321

**Comment by stevschmid** [comment]
Were you using 0.4.7?

**Comment by denton** [comment]
Yes

**Comment by stevschmid** [comment]
I'm a little bit at loss here. Can you send me the log file next time this happens? Copy the log file before you close down Hearthstone.

**Comment by denton** [comment]
Of course, this time I saw this bug too late to send log file, next time I will send you more detailed info. 
PS: Can you please delete this recorded game, I want to continue my arena run and it broken now.
Thank you.

**Comment by stevschmid** [comment]
I cannot, sorry. Don't worry about the stats though. They will eventually even out :)

**Comment by denton** [comment]
Sorry, I don't get it. With great respect for you, I don't understand why you cannot delete obviously incorrect record.
Alarm-o-bot, while IMHO being best tracking software for HS, in its current state, on one hand, has tons of ways to mess his stats, on the other hand, doesn't have any tool for clearing this mess. I understand that you doesn't have time to manually resolve problems like this, but may be you have some other solution for this.
Once again, no offence, just curiosity.

**Comment by stevschmid** [comment]
Part of my development philosophy is that I will not tamper with databases. I understand your frustration though! There is somebody working on a [delete ability](https://github.com/stevschmid/trackobot.com/issues/12) which would be really helpful, but I don't have the time right now to finish it.

**Comment by stevschmid** [comment]
You can now delete results (if you delete all matches of a specific arena run, the arena run is deleted as well).
