### ISSUE TITLE
Sometimes preview of cards played in a match are incorrect

### ISSUE THREAD

**Issue by K-T-O** [stevschmid/track-o-bot#89]
![this_was_not_a_warlock_opponent](https://cloud.githubusercontent.com/assets/13416854/8835378/fa4749e2-30b1-11e5-9318-26678d75bff6.png)

**Comment by oker1** [comment]
Can confirm, but what actually happens is that the last match is mixed up with the previous. The previous match is not in the list, but the opponents played cards are showed for the last match.

**Comment by stevschmid** [comment]
So it missed the ending of the previous game? Interesting, thanks for sharing. Will look into this for the upcoming version.

**Comment by KrzysztofTOlszewski** [comment]
I remember a case when I restarted PC during the game. I am not sure if that was the case here. Anyway, could that have caused it?

**Comment by mariosuello** [comment]
In my case, trak-o-bot mixed the last game that i played with one that i spectated.
![cattura](https://cloud.githubusercontent.com/assets/14131857/9745408/01a2b7a4-5672-11e5-8233-bb6f776578ec.PNG)

**Comment by stevschmid** [comment]
Check out the new version (0.6.0). Reopen the issue if it still persists.
