### ISSUE TITLE
Suggestion: Shared Decks

### ISSUE THREAD

**Issue by geraldhiller** [stevschmid/track-o-bot#94]
Have you considered making decks public, or sharing them between users?

I reckon it would benefit most users to have the standard decks of the current meta in your profile by default (Handlock, Zoolock, Face Hunter, etc.). It means less configuration for each user and the vs. data would be more accurate from the start.

Deck spam could be prevented by only making decks public once they see enough play, such as 100 games or a 1000 games (depending on the data).

**Comment by mariosuello** [comment]
it's a beautiful idea

**Comment by stevschmid** [comment]
This is a good idea. However, I would prefer a moderated list of decks you can import into your own profile. What do you guys think?

**Comment by geraldhiller** [comment]
Of course that's better for the start, but that would require extra work for you in terms of being aware of the Hearthstone meta. I'm sure you have plenty to do with the app. 

The beauty of trackobot is that the player has to do nothing. That's how I imagine a crowd sourced decklist to work. 

But given how slow the meta develops it would probably be a lot less work for you to just provide a list of 10 or 20 decks for users to pick from, than developing and curating the algorithm and doing the maintenance for a proper crowd sourced list. 

If you do decide to provide a moderated public decklist, it could be of some benefit to have a little tool that tells you the most popular decklists over all users of trackobot (or at least common denominators with a minimum of 3 cards in common). Thay way, even if you are not up to speed with the most current meta that would alert you to new popular decks, and make it easier to add them to the list. 


For me the greatest benefit trackobot provides is that it answers a lot of the open questions I have about my play via statistical methods. It would be great if it could do the same for the meta - in one way or another.

**Comment by ovidiusoft** [comment]
I found this great post, so there is a lot of interest regarding this feature: https://www.reddit.com/r/trackobot/comments/3jcufd/current_meta_keywords/ . I am sure the list can be croudsourced and updated on the server once in a while.

**Comment by stevschmid** [comment]
I'm planning on revamping the whole deck bit on the website.
