### ISSUE TITLE
Issue with selecting only one day in stats on web page

### ISSUE THREAD

**Issue by geraldhiller** [stevschmid/track-o-bot#96]
One day selected: http://take.ms/lM1ta
24 hours selected: http://take.ms/B35UW
Recent history: http://take.ms/M1AEk

**Comment by stevschmid** [comment]
Thanks for the report. Can you please reopen the issue at https://github.com/stevschmid/trackobot.com?

**Comment by geraldhiller** [comment]
Done. By the way, have you considered tracking Tavern Brawl games as well?

**Comment by stevschmid** [comment]
Tavern Brawls are not really trackable. In the [first](http://hearthstone.gamepedia.com/Showdown_at_Blackrock_Mountain) one for example you couldn't choose a (otherwise playable) class. So I disabled the tracking for this mode altogether.

**Comment by geraldhiller** [comment]
Can't you abstract the class concept for that?

**Comment by stevschmid** [comment]
Tavern Brawl is a casual and fun game mode which changes on a weekly basis. I don't see much merit in tracking the records mode which changes on a weekly basis?

**Comment by geraldhiller** [comment]
Well, that's the way Blizzard sees it, but apparently there is tracking
https://twitter.com/CM_Zeriyah/status/611637903265894400.

For me it's interesting information, after a few hours of TB, to know if I
am 12/6 or 12/14.

**Comment by stevschmid** [comment]
Oh wow! I'm surprised there is a hidden MMR. I see your use case, but I think the effort (both in client and website) is not worth it. But ultimately I'm open to it if more people want this.
