### ISSUE TITLE
HSReplay support

### ISSUE THREAD

**Issue by jleclanche** [stevschmid/track-o-bot#97]
Hi there

I'm the founder of the [Hearthsim community](http://hearthsim.info). We are currently working on a serious replay format called HSReplay, which Hearthstone-Deck-Tracker is going to be using as well. It is an xml format, based on the Power.log format. 

Here is an example of a brawl match in it:
https://leclan.ch/public/underdog-rules.xml

The spec, python converter and csharp implementation as well as the dtd file are available in the [HearthSim/HSReplay](https://github.com/hearthsim/hsreplay) repository. You'd be welcome to participate - we have the `#hearthsim` IRC channel on chat.freenode.net.

**Comment by stevschmid** [comment]
Thanks for the info. Will look into this if I intend to expand the feature set of Track-o-Bot.

**Comment by jleclanche** [comment]
No problem. We released version 1.0 since I filed this:

http://hearthsim.info/hsreplay/
