### ISSUE TITLE
[Bug][0.6.0][Windows 10] Crash when enabling "Start at login" 

### ISSUE THREAD

**Issue by gssjr** [stevschmid/track-o-bot#98]
"Track-o-Bot has stopped working" error / crash when trying to check "Start at login" on Windows 10 Pro x64

**Comment by gssjr** [comment]
My mac updated to 0.6.1 claiming a fix for the windows start up issue but it doesn't look like that version was actually released for the windows build yet

**Comment by stevschmid** [comment]
Thanks for the report. There is Qt bug currently affecting the rollout of the new version on Windows. Hope to push it out soon.
